FROM node:22.15.1 AS build
WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY . .
RUN npm run dev

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]
