FROM node:22.15.1 AS build
WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY ./frontend .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 5173
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
