version: '3.8'

services:
  db:
    image: postgres:13
    container_name: chat-app-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1122
      POSTGRES_DB: chat_app_go
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data  
    networks:
      - jwt-network

  mongoDb:
    image: mongo:6
    container_name: chat-app-mongoDb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  
    networks:
      - jwt-network

  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: chatting-app
    ports:
      - "8002:8002"
    depends_on:
      - db
      - mongoDb
    env_file:
      - .env
    networks:
      - jwt-network

volumes:
  pg_data:
  mongo_data:

networks:
  jwt-network:
