apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatting-app
  template:
    metadata:
      labels:
        app: chatting-app
    spec:
      containers:
        - name: chatting-app
          image: siddique292/chat_application_go-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: app-env
---
apiVersion: v1
kind: Service
metadata:
  name: chatting-app
spec:
  selector:
    app: chatting-app
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
