FROM golang:1.24.2 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod tidy
COPY . .
RUN CGO_ENABLED=0 go build -o websocket-service main.go
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY .env . 
COPY --from=builder /app/websocket-service .
EXPOSE 8004
CMD ["./websocket-service"]
